Repository rderekp/The-Grand-Combo, pull requests merged in 2023-01, with the labels that each got.

#196 [DO NOT MERGE] Improved README.md
  README.md
Labels: documentation, enhancement

#214 Loc fixed.
  TGC/events/Germany VS Hungary Events.txt
  TGC/localisation/00_events_1000000000.csv
Labels: enhancement, good first issue

#217 Core Fixes
  TGC/history/provinces/africa/2021 - Masindi.txt
  TGC/history/provinces/africa/2109 - Lydenburg.txt
  TGC/history/provinces/south america/2205 - Bocas del Toro.txt
  TGC/history/provinces/south america/2206 - Archipielagos de Bocas del Toro.txt
  TGC/history/provinces/south america/2297 - Ica.txt
  TGC/history/provinces/south america/3400 - Abra Pampa.txt
  TGC/history/provinces/soviet/1069 - Vilyuysk.txt
  TGC/history/provinces/soviet/2619 - Abiy.txt
  TGC/history/provinces/soviet/2621 - Srednekolymsk.txt
  TGC/history/provinces/soviet/2642 - Ust Nera.txt
  TGC/history/provinces/soviet/2644 - Olyekminsk.txt
  TGC/history/provinces/soviet/2645 - Chilchi.txt
  TGC/history/provinces/soviet/2648 - Yakutsk.txt
  TGC/history/provinces/soviet/2649 - Zhigansk.txt
  TGC/history/provinces/soviet/2650 - Nyurba.txt
  TGC/history/provinces/soviet/2651 - Udanchniy.txt
  TGC/history/provinces/soviet/2652 - Kular.txt
  TGC/history/provinces/soviet/2653 - Saskylah.txt
  TGC/history/provinces/soviet/2667 - Bulun.txt
  TGC/history/provinces/soviet/2672 - Pokrovsk.txt
  TGC/history/provinces/soviet/2673 - Olenyok.txt
  TGC/history/provinces/soviet/2695 - Mukhtuya.txt
  TGC/history/provinces/soviet/2696 - Aldan.txt
Labels: Enhancement, Good first issue, Map

#219 loc and id fixes
  TGC/events/East Indies.txt
  TGC/events/Goods.txt
  TGC/localisation/00_events_0090000.csv
  TGC/localisation/00_events_1000000.csv
  TGC/localisation/00_modifiers.csv
  TGC/localisation/00_newspaper.csv
Labels: Enhancement, Good first issue, Localization, Content

#221 Last modifier locs
  TGC/common/event_modifiers.txt
  TGC/localisation/00_modifiers.csv
Labels: Enhancement, Localization

#238 First Batch of Content for Argentina [Check description]
  TGC/common/event_modifiers.txt
  TGC/decisions/Argentina.txt
  TGC/decisions/ArgentineConfederation.txt
  TGC/events/ARGCivilWar.txt
  TGC/events/ARGFlavor.txt
  TGC/gfx/pictures/decisions/arc_death.dds
  TGC/gfx/pictures/decisions/arc_talks.dds
  TGC/gfx/pictures/decisions/belgrano_tucuman.dds
  TGC/gfx/pictures/decisions/constitution.dds
  TGC/gfx/pictures/decisions/estancia.dds
  TGC/gfx/pictures/events/arc_victory.dds
  TGC/gfx/pictures/events/army_gates.dds
  TGC/gfx/pictures/events/federalism_vs_unitarism.dds
  TGC/gfx/pictures/events/literary_hall.dds
Labels: Enhancement, Content
